# This file is a template, and might need editing before it works on your project.
# use the official gcc image, based on debian
# can use verions as well, like gcc:5.2
# see https://hub.docker.com/_/gcc/
image: gcc

build:
  stage: build
  tags:
    - iot
  # instead of calling g++ directly you can also use some build toolkit like make
  # install the necessary build tools when needed
  # before_script: 
  #   - apt update && apt -y install make autoconf 
  script: 
    - ls
    - pwd
    - echo "path:"
    - export PATH="/opt/xtensa-esp32-elf/bin:$PATH"
    - echo $PATH
    - python /home/gitlab-runner/test.py
    - echo "test idf1"
    - echo $IDF_PATH
    - source ~/.bash_profile
    - echo "test idf2"
    - echo $IDF_PATH
    - echo "test111"
    - make defconfig
    - make -j8
  # depending on your build setup it's most likely a good idea to cache outputs to reduce the build time
  # cache:
  #   paths:
  #     - "*.o"

# run tests using the binary built before
#test:
#  stage: test
#  tags:
#    - iot
#  script:
#    - ls
#    - pwd
#    - echo "test2"
