# example/a               // project full path
#  target: esp32          // target name
#  sdkconfig:             // sdkconfig name
#     - a                 // sdkconfig.ci.a
#     - default           // sdkconfig.default
#  target: esp32s3        // target name
#  sdkconfig:             // sdkconfig name
#     - b                 // sdkconfig.ci.a
#     - default           // sdkconfig.default
#  readme:                // readme url must point a README.md link
#     <URL>

examples/usb/device/usb_dual_uvc_device:
  esp32s3:
    sdkconfig:
      - esp32s3_usb_otg
  esp32p4:
    sdkconfig:
      - defaults
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/device/usb_dual_uvc_device/README.md

examples/usb/device/usb_webcam:
  esp32s3:
    sdkconfig:
      - esp32s3_eye
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/device/usb_webcam/README.md

examples/usb/host/usb_camera_lcd_display:
  esp32s3:
    sdkconfig:
      - esp32s3_lcd_ev_board
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/host/usb_camera_lcd_display/README.md

examples/usb/host/usb_camera_mic_spk:
  esp32s3:
    sdkconfig:
      - esp32s3_usb_otg
      - defaults
  readme:
    https://raw.githubusercontent.com/espressif/esp-iot-solution/master/examples/usb/host/usb_camera_mic_spk/README.md
